name: "Test action"
description: "Execute the test"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "some description"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"